# ############################################################
# # +------------------------------------------------------+ #
# # |              AdminInv Configuration                  | #
# # |               Developer Fabian996                    | #
# # +------------------------------------------------------+ #
# ############################################################

Metrics:
    enable: true
    
vote:
    message1: Link1
    message2: Link2
    message3: Link3
    message4: Link4
    message5: Link5
    
serverinfo:
    website: Link
    teamspeak: Ip
    forum: Link
    
database:
    mysql:
      host: localhost
      username: username
      passwort: passwort
      port: 3306
