# ############################################################
# # +------------------------------------------------------+ #
# # |            AdminInv 2 Configuration                  | #
# # |              Developer Fabian996                     | #
# # +------------------------------------------------------+ #
# ############################################################
# # Legende:
# # Colors: red, dark_red, aqua, dark_aqua, green, dark_green, gray, dark_gray, purple, light_purple, black, gold, yellow, blue, dark_blue
# # %target% = /kick <player>

Metrics:
    Status: true

Wartung:
    Status: false
    Message: Der Server befindet sich gerade im Wartungsmodus

############################################################
# +------------------------------------------------------+ #
# |              Vote Links Configuration                | #
# +------------------------------------------------------+ #
############################################################
vote:
    message1: Link1
    message2: Link2
    message3: Link3
    message4: Link4
    message5: Link5
    
############################################################
# +------------------------------------------------------+ #
# |          Server Information Configuration            | #
# +------------------------------------------------------+ #
############################################################   
serverinfo:
    website: homepage-link
    teamspeak: ts-ip
    forum: forum-link


############################################################
# +------------------------------------------------------+ #
# |                 Message Configuration                | #
# +------------------------------------------------------+ #
############################################################ 
Message:
    KickMessage: '&6%target% &7wurde vom Server gekickt'

############################################################
# +------------------------------------------------------+ #
# |              Inventory Configuration                 | #
# +------------------------------------------------------+ #
############################################################
Inventory:
    ExtraInv: false
    

############################################################
# +------------------------------------------------------+ #
# |            Einstellung Configuration                 | #
# +------------------------------------------------------+ #
############################################################
Einstellung:
    Chat_Log: true
    Command_Log: true
    
