# ############################################################
# # +------------------------------------------------------+ #
# # |              AdminInv Configuration                  | #
# # |               Developer Fabian996                    | #
# # +------------------------------------------------------+ #
# ############################################################

Metrics:
    enable: true

# ############################################################
# # +------------------------------------------------------+ #
# # |              Vote Links Configuration                | #
# # +------------------------------------------------------+ #
# ############################################################   
vote:
    message1: Link1
    message2: Link2
    message3: Link3
    message4: Link4
    message5: Link5

# ############################################################
# # +------------------------------------------------------+ #
# # |          Server Information Configuration            | #
# # +------------------------------------------------------+ #
# ############################################################   
serverinfo:
    website: Link
    teamspeak: Ip
    forum: Link
