# ############################################################
# # +------------------------------------------------------+ #
# # |            AdminInv 2 Configuration                  | #
# # |              Developer Fabian996                     | #
# # +------------------------------------------------------+ #
# ############################################################
# # Legende:
# # Colors: red, dark_red, aqua, dark_aqua, green, dark_green, gray, dark_gray, purple, light_purple, black, gold, yellow, blue, dark_blue
# # %target% = /kick <player>

Metrics:
    Status: true

Wartung:
    Status: false
    Message: Der Server befindet sich gerade im Wartungsmodus

AutoBackup:
    Interval: 60

AutoBroadcast:
    Status: false
    Interval: 180
    Nachrichten:
        - '&6Nachricht1'
        - 'Nachricht2'

############################################################
# +------------------------------------------------------+ #
# |              Vote Links Configuration                | #
# +------------------------------------------------------+ #
############################################################
Voten:
    Nachricht: Link1
    Nachricht1: Link2
    Nachricht2: Link3
    Nachricht3: Link4
    Nachricht4: Link5
    
############################################################
# +------------------------------------------------------+ #
# |          Server Information Configuration            | #
# +------------------------------------------------------+ #
############################################################   
serverinfo:
    website: homepage-link
    teamspeak: ts-ip
    forum: forum-link


############################################################
# +------------------------------------------------------+ #
# |             Nachrichten Configuration                | #
# +------------------------------------------------------+ #
############################################################ 
Nachrichten:
    KickNachricht: '&6%target% &7wurde vom Server gekickt'

############################################################
# +------------------------------------------------------+ #
# |               Inventar Configuration                 | #
# +------------------------------------------------------+ #
############################################################
Inventar:
    ExtraInv: false


############################################################
# +------------------------------------------------------+ #
# |            Einstellung Configuration                 | #
# +------------------------------------------------------+ #
############################################################
Einstellung:
    Chat_Log: false
    Command_Log: false
