name: AdminInv2
version: 1.0
main: com.jimdo.Fabian996.AdminInv2.Main.AdminInv
author: Fabian996
website: http://bit.ly/1m13hON
depend: [Vault]

commands:
  aspy:
    description: Sie konnen sich anzeigen lassen was der Spieler fur ein Befehl nutzt
    
  areload:
    description: Neuladen der Config
    
  ahelp:
    description: Zeigt alle Befehle an
    
  pinfo:
    description: Zeigt die Spieler Information an
    
  br:
    description: Senden einer Broadcast
    
  cc:
    description: Loscht den Chat
    
  glmute:
    description: Globale Mute, Teammitglieder konnen schreiben
    
  heal:
    description: Du kannst dich heilen oder andere Spieler
    
  ping:
    description: Zeigt dir den Ping an MC Version 1.9.x
    
  tc:
    description: Du kannst mit deinen Teammitglieder schreiben
    
  wartung:
    description: Hier mit kannst du den Wartungs Modus an/aus machen
    
  egm:
    description: Du kannst in den verscheidene Gamemode wecheln
    
  sinfo:
    description: Zeigt dier Serverinformation an
    
  vote:
    description: Zeigt dier Serverinformation an 
    
  invsee:
    description: Zeigt dir das Inventar und Ender Chest
    
  kick:
    description: Spieler kicken mit Grund vom server
    
  aban:
    description: Spieler von Server Bannen

  uban:
    description: Spieler von Server Unbannen

  setinfo:
    description: Andern der Serverinformation

  rename:
    description: Andert den namen des Items in der Hand

  msg:
    description: Private Nachrichten senden

  r:
    description: Private Nachrichten senden
    

permissions:
  admininv.*:
    description: Gibt Zugang zu allen Befehlen von AdminInv 
    default: OP
    children:
      admininv.admin: true
      admininv.spielerinfo: true
      admininv.broadcast: true
      admininv.cc: true
      admininv.globalmute: true
      admininv.heal: true
      admininv.healother: true
      admininv.tc: true
      admininv.wartung: true
      admininv.invsee: true
      admininv.kick: true
      admininv.ban: true
      admininv.setinfo: true
      admininv.rename: true
